# Arrays
## basics


In [1]:
import array as arr

In [2]:
a=arr.array('i',[5,6,7])     #creating an array a
a

array('i', [5, 6, 7])

In [4]:
b=arr.array('i',[7,8,9])     #creating an array b
b

array('i', [7, 8, 9])

# slicing

In [5]:
a[0:]                       #slicing

array('i', [5, 6, 7])

In [6]:
a[::1]                     #slicing in the forward direction

array('i', [5, 6, 7])

In [7]:
a[::-1]                    #slicing in the reverse direction

array('i', [7, 6, 5])

In [8]:
a[:0]                      #slicing at 0

array('i')

In [9]:
a[:1]                       #slicing at 1

array('i', [5])

In [11]:
a.append(6)                 #append of 6
a

array('i', [5, 6, 7, 6, 6])

In [16]:
b.pop()                     #pop operation
b

array('i', [7, 8])

In [29]:
a.pop()                     #pop operation
a

array('i')

In [20]:
a                     

array('i', [5, 6, 7, 6])

In [21]:
a.remove(a[1])             #remove operation
a                      

array('i', [5, 7, 6])

In [23]:
a              

array('i', [5, 7, 6])

In [25]:
a.remove(a[2])             #remove operation
a

array('i', [5, 7])

In [28]:
a.pop()                   #pop operation
a

array('i', [5])

In [30]:
a

array('i')

In [31]:
b.pop()                    #pop of last element

8

In [32]:
b

array('i', [7])

In [34]:
b

array('i', [7])

In [35]:
c=arr.array('i',[1,2,3])               #creating an array c
c                                      

array('i', [1, 2, 3])

In [36]:
c.pop(1)
c                                      #pop of c

array('i', [1, 3])

In [37]:
a

array('i')

In [38]:
b

array('i', [7])

In [39]:
b.pop(0)                            #pop operation
b

array('i')

In [44]:
for i in c:                       #getting all elements in c
    print(i)                          

1
3


In [46]:
for i in c:                     # getting all elements in c horizontally
    print(i,end=" ")             

1 3 

In [47]:
a+b                           #addition operation 

array('i')

In [48]:
c+a                          #addition operation

array('i', [1, 3])

In [50]:
c+b                         #addittion operation

array('i', [1, 3])

# Numpy
`pip install numpy`

In [51]:
import numpy as np         #importing numpy

In [52]:
g=np.array([(4,5,6),(7,8,9)])      #creating a matrix g using numpy
h=np.array([(1,2,3),(2,5,6)])      #creating a matrix h using numpy
g

array([[4, 5, 6],
       [7, 8, 9]])

In [53]:
h

array([[1, 2, 3],
       [2, 5, 6]])

In [55]:
g.ndim                           #finding which dimensional martix is g

2

In [56]:
g.itemsize                      #finding the size of an element of g

4

In [57]:
h.itemsize                     # finding the size of an element of h

4

In [58]:
h.dtype                       #finding datatype of h

dtype('int32')

In [59]:
g.size                      #finding size of g
g

array([[4, 5, 6],
       [7, 8, 9]])

In [60]:
h.shape                    #finding number of rows and columns of h

(2, 3)

In [61]:
h.reshape(3,2)            #changing rows into columns and columns into rows

array([[1, 2],
       [3, 2],
       [5, 6]])

In [63]:
g.min()                   #finding min value of g

4

In [64]:
g.max()                  #finding max value of g

9

In [66]:
h.sum()                  #finding the sum of h matrix

19

In [68]:
i=np.linspace(2,7,10)   #getting 10 values between 2 and 7
i

array([2.        , 2.55555556, 3.11111111, 3.66666667, 4.22222222,
       4.77777778, 5.33333333, 5.88888889, 6.44444444, 7.        ])

In [69]:
g.sum(axis=1)           #getting sum of elements of rows in g

array([15, 24])

In [70]:
g.sum(axis=0)           #getting sum of elements of columns in g

array([11, 13, 15])

In [71]:
np.sqrt(g)              # finding square root of all eements in g

array([[2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [73]:
np.std(h)               #finding standerd deviation of h

1.7716909687891083

In [74]:
np.mean(g)             #finding total mean of g

6.5

In [75]:
g

array([[4, 5, 6],
       [7, 8, 9]])

In [76]:
h

array([[1, 2, 3],
       [2, 5, 6]])

In [77]:
g[0,2]              #finding 2nd element of 0th column

6

In [81]:
h[0:2,1]

array([2, 5])

In [83]:
g[1:2,1]

array([8])

In [85]:
g[g>1]              #finding the elements greater than 1

array([4, 5, 6, 7, 8, 9])

In [87]:
h.sort()           #sorting of elements in ascending order
h

array([[1, 2, 3],
       [2, 5, 6]])

In [88]:
h[h<1]                    #finding the elements less than 1

array([], dtype=int32)

In [89]:
g+h                      # adding of two matrices


array([[ 5,  7,  9],
       [ 9, 13, 15]])

In [90]:
g*h                     #multiplication of two matrices

array([[ 4, 10, 18],
       [14, 40, 54]])

In [91]:
g.ravel()              #getting all elements in a same matrix

array([4, 5, 6, 7, 8, 9])

In [96]:
h.ravel()              #getting all elements of h in one matrix

array([1, 2, 3, 2, 5, 6])

In [97]:
a

array('i')

In [98]:
b

array('i')

In [100]:
c.pop()                #pop operation

3